import Link from "next/link";
import { GET } from "../api/users/route";

export const metadata = {
  title: "Users",
  description: "Generated by create next app",
};



const page = async () => {
  const res=await GET();
  const users=await res.json();
  // console.log(users)
 

  return (
    <>
    {users.map((user) =>{
        return <div className="col-md-4 mb-3"key={user._id} >
        <div className="card" style={{width: '18rem'}}>
          <div className="card-body">
            <h5 className="card-title">{user.name}</h5>
            <p className="card-text">
            Email: {user.email} <br/>
            Company: {user.company} <br/>
            </p>
            <Link href={`/users/${user._id}`} className="btn btn-primary">
             Details
            </Link>
          </div>
        </div>
      </div>
    })}
    </>
  );
};

export default page;
