'use client'

import { Roboto } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "@/Components/Footer/Footer";
import Navbar from "@/Components/Nav/Navbar";
import { usePathname } from 'next/navigation';

const roboto = Roboto({
  weight: ["700", "500", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const hide = pathname === '/signup';
  return (
    <html lang="en">
      <body className={roboto.className}>
        
        {!hide && <div className="mb-5 fixed-top"> <Navbar /></div>}
        
        <div className="container mt-md-5 mb-5 pt-5">
          <div className="row">
            {children}
          </div>
        </div>
        {!hide && <Footer />}

      </body>
    </html>
  );
}
